[Account]
Device = 85080ba0-9382-4cd9-afd3-119c203d9fea
PrivateKey = YLgCZN10CYGV26xblNtjAp6XEIZoQQG/jxWLXK3mrm0=
Token = fe8c310c-15b5-4b65-a4fd-6eb2a87c1b50
Type = free
Name = WARP
MTU = 1280

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
Endpoint = 162.159.192.8:0
Endpoint6 = [2606:4700:d0::a29f:c008]:0
# AllowedIPs = 0.0.0.0/0
# AllowedIPs = ::/0
KeepAlive = 30
