[Account]
Device = 533cb2e8-80fd-47d9-ac3b-d87cdb2644e7
PrivateKey = KKDq14SZ8wlrIH3meTFQyAi5NI6Y3QMu//5jMkH5x0E=
Token = 7bf61fdf-cb27-4a49-8ed5-40d0479c0a62
Type = free
Name = WARP
MTU = 1280

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
Endpoint = 162.159.192.8:0
Endpoint6 = [2606:4700:d0::a29f:c008]:0
# AllowedIPs = 0.0.0.0/0
# AllowedIPs = ::/0
KeepAlive = 30
